### ISSUE TITLE
infrastructure proposal: create a blog for this book

### ISSUE THREAD

**Issue by gvwilson** [roc-lang/book-of-examples#20]
RSS is an easy way for interested parties to keep up with occasional announcements and progress reports. We can easily set up a GitHub Pages blog (https://roc-lang.github.io/book-of-examples/) using Jekyll for now, and switch to a Roc-based tool if there's interest while recycling the posts. I envision posts consisting of things like "person X has taken on topic Y", "person Q has a first draft of topic P ready for review", and, "we've made the following decisions about managing the glossary".

Please add thoughts below: in particular, is this Yet Another Distraction and everything should stay in Zulip or some other channel?

**Comment by lukewilliamboswell** [comment]
I think my preference would be to use zulip for these updates, as that is already the goto place for most roc discussion and announcements. 

Who is the intended audience? Why do we want to give these updates? Is this to request assistance with reviews or comments? 

I also receive emails for changes in github so commentary or more detailed discussion there is also easy to follow.

**Comment by isaacvando** [comment]
I agree, I would prefer these updates to go to a dedicated stream in Zulip.

**Comment by HajagosNorbert** [comment]
I'd prefer if I had to only look at Zulip and Github as well. 3 sources feels too much.

**Comment by gvwilson** [comment]
Thanks for the feedback - Zulip and GitHub it is.
