### ISSUE TITLE
proposal: use Jekyll/GitHub Pages _temporarily_ to build a website for this material

### ISSUE THREAD

**Issue by gvwilson** [roc-lang/book-of-examples#50]
I propose using standard GitHub Pages tooling (i.e., [Jekyll](https://jekyllrb.com/)) to build a website for this material while we are working on rough drafts, and to move to something Roc-based once we have a better idea of what we need.

Pros:

1. Immediately available: see the `website` branch of this repo, which uses a template from previous book-ish projects I've worked on.
2. Having something up right away will give us a better idea of what we actually want from whatever static site generator we eventually choose.
3. "Use GHP's default" can save a _lot_ of arguing over what's the best SSG and why.

Cons:

1. Local preview requires Jekyll.
   - Contributors shouldn't be worried about formatting at this point (@gvwilson can tidy that up as PRs come in if necessary).
   - Jekyll is straightforward to set up for people who do want to preview.
2. We ought to use a Roc-based SSG.
   - Translation will be low effort, since the templating is very simple.
   - Building this with an off-the-shelf tool will give us a better idea of what we actually need in that SSG.

**Comment by jwoudenberg** [comment]
This sounds great to me! I like the idea of having something setup early, and then possibly revisit later when we have a roc-based tool that'd be a better fit.

**Comment by gvwilson** [comment]
closed by 96e9963ab2 - I went with server-side rendering and serving out of `docs` for now so that I can check things as they come in. I look forward to replacing this all with a Roc-based static site generator :-)
